# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always

    volumes: 
        - ./data/criacaoDoBanco.sql:/docker-entrypoint-initdb.d/criacaoDoBanco.sql
        - ./data/criacaoDasTabelasDeDimensao.sql:/docker-entrypoint-initdb.d/criacaoDasTabelasDeDimensao.sql
        - ./data/popularTabelas.sql:/docker-entrypoint-initdb.d/popularTabelas.sql
    environment:
      POSTGRES_PASSWORD: example
    ports: 
        - 5432:5432
